// ==UserScript==
// @name         Movie Club — Add from Google
// @namespace    https://cobresun-movie-club.netlify.app
// @version      0.1.0
// @description  Adds a "View in MovieClub" button to Google's movie knowledge panel.
// @match        https://www.google.com/search*
// @match        https://www.google.ca/search*
// @match        https://www.google.co.uk/search*
// @match        https://www.google.com.au/search*
// @match        https://www.google.de/search*
// @match        https://www.google.fr/search*
// @match        https://www.google.co.in/search*
// @grant        none
// @run-at       document-idle
// ==/UserScript==

// Injects a "View in MovieClub" button into Google's movie knowledge panel.
// Shared verbatim between the MV3 extension (loaded via manifest.json) and the
// Tampermonkey userscript (movie-club.user.js, generated by
// `npm run build:userscript`).
(() => {
  "use strict";

  // Override for local development without editing this file — run this in
  // the DevTools console on google.com, then reload:
  //   localStorage.setItem("movieClubBaseUrl", "http://localhost:8888")
  const BASE_URL =
    localStorage.getItem("movieClubBaseUrl") ??
    "https://cobresun-movie-club.netlify.app";
  const BUTTON_ID = "movie-club-add-btn";
  const IMDB_ID = /tt\d{7,10}/;

  function findMovie() {
    // Google marks movie knowledge-panel modules with kc:/film/film data
    // attributes (ratings row, cast strip, ...). Absent => not a movie page.
    const filmModule = document.querySelector('[data-attrid^="kc:/film/film"]');
    if (!filmModule) return null;

    const titleEl = document.querySelector('[data-attrid="title"]');
    const title = titleEl?.textContent?.trim();
    if (!title) return null;

    // Subtitle like "1994 ‧ Crime/Drama ‧ 2h 22m".
    const subtitle =
      document.querySelector('[data-attrid="subtitle"]')?.textContent ?? "";
    const year = subtitle.match(/\b(19|20)\d{2}\b/)?.[0];

    // The ratings row links to imdb.com/title/tt<id> — an exact identity the
    // app resolves via TMDB. Works through Google's /url?q= redirects too,
    // since the substring survives inside the q param.
    const imdbHref = document.querySelector(
      'a[href*="imdb.com/title/tt"]',
    )?.href;
    const imdbId = imdbHref ? (imdbHref.match(IMDB_ID)?.[0] ?? null) : null;

    return { title, year, imdbId, anchor: titleEl };
  }

  function buildHref({ imdbId, title, year }) {
    const params = new URLSearchParams();
    if (imdbId) params.set("imdb", imdbId);
    params.set("title", title);
    if (year) params.set("year", year);
    return `${BASE_URL}/add?${params.toString()}`;
  }

  function inject() {
    if (document.getElementById(BUTTON_ID)) return true; // idempotent — also
    // prevents doubles when both the extension and the userscript are active
    const movie = findMovie();
    if (!movie) return false; // silent no-op on non-movie pages

    const link = document.createElement("a");
    link.id = BUTTON_ID;
    link.href = buildHref(movie);
    link.target = "_blank";
    link.rel = "noopener";
    link.textContent = "View in MovieClub";
    // Inline styles only — no stylesheet injection, no SERP CSS collisions.
    // An opaque brand-blue pill with white text reads on both light and dark
    // SERP themes (#2196F3 is the app's Tailwind `primary`).
    link.style.cssText = [
      "display:inline-block",
      "margin:8px 0",
      "padding:6px 14px",
      "border-radius:16px",
      "background:#2196F3",
      "color:#fff",
      "font:500 14px/20px Roboto,Arial,sans-serif",
      "text-decoration:none",
      "cursor:pointer",
    ].join(";");
    movie.anchor.parentElement?.insertAdjacentElement("afterend", link);
    return true;
  }

  if (inject()) return;
  // Knowledge panels frequently hydrate after document_idle; watch briefly.
  const observer = new MutationObserver(() => {
    if (inject()) observer.disconnect();
  });
  observer.observe(document.body, { childList: true, subtree: true });
  setTimeout(() => observer.disconnect(), 15000); // give up quietly
})();
